name: pr_to_master

on:
  pull_request:
    branches:
      - main

env:
  # Environment variables for running Dbt on Google BigQuery
  DBT_GOOGLE_PROJECT_DEV: pacc-analytics
  PACC_SA_RAW: service_account.json
  DBT_BIGQUERY_DATASET_DEV: github_action

jobs:
  pr_to_master:
    name: pr_to_master
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v2

      - uses: actions/setup-python@v1
        with:
          python-version: "3.9.x"

      # Dbt - Google BigQuery
      - name: Authenticate gcloud
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.PACC_SA_RAW }}
          project_id: ${{ env.DBT_GOOGLE_PROJECT_DEV }}
      
      - name: Create Google Service Account key file from secret
        run: 'echo "$KEYFILE" > ${{ env.PACC_SA_RAW }}'
        shell: bash
        env:
          KEYFILE: ${{ secrets.PACC_SA_RAW }}

      ## Cache Pip wheel files
      - name: Cache Pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      ## Install Python dependencies & Dbt packages
      - name: Install dependencies
        run: |
          pip3 install -r requirements.txt

      ## Lint model files
      - name: Run Base VN Packages
        run: |
          ./bash_scheduling/base_vn_run.sh

